### ISSUE TITLE
How to use ICNet with Camvid database?

### ISSUE THREAD

**Issue by emersonjr** [lxtGH/Fast_Seg#21]
i'm trying to use ICNet with Camvid database but it seems although specifying camvid, `val.py` pushes me to use Cityscapes anyways. I receive this error:

```
Traceback (most recent call last):
  File "val.py", line 264, in <module>
    val()
  File "val.py", line 231, in val
    for index, batch in enumerate(testloader):
  File "E:\Python64\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "E:\Python64\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "E:\Python64\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\Python64\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\Mestrado\Fast_Seg-master\libs\datasets\cityscapes.py", line 70, in __getitem__
    label = self.id2trainId(label)
  File "E:\Mestrado\Fast_Seg-master\libs\datasets\cityscapes.py", line 57, in id2trainId
    label_copy = label.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

What could I do to solve this?

**Comment by lxtGH** [comment]
This is because I do not import the camvid dataset. Please pull the latest code.
