### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by pawopawo** [lxtGH/Fast_Seg#8]
https://github.com/lxtGH/Fast_Seg/blob/9b3673947dd51ef9609943e3ad4a7e4530ea8468/val.py#L238

```
Traceback (most recent call last):
  File "val.py", line 273, in <module>
    val()
  File "val.py", line 240, in val
    image, label, size, name = batch
ValueError: not enough values to unpack (expected 4, got 2)
```

**Comment by lxtGH** [comment]
The bug has been fixed
